### ISSUE TITLE
Implement QR detector and pass JSON back

### ISSUE THREAD

**Issue by dscwebdev** [uw-datasci/uwdsc-website-v2#52]
### Admin page -> QR detection page -> User information -> Check-in user
From the admin page, the admin should be able to click a button to be routed to the QR detection page.
From the QR detection page, the camera will open and try to scan for a QR code.
Once scanned, it should display `username`, `uwEmail`, `faculty`, `hasPaid`, and `isCheckedIn` of the user. (/api/admin/getUserById/:id)

1. If the user has not paid - Display message that user needs to pay
2. If the user has paid, but is not checked in - Display button to check them in
3. If the user has paid and is checked in - Display message that user has already checked in to current event

Check in button sends a PUT to (/api/admin/checkInById/:id)

At all times there should be a button to return to camera.

**Comment by mrkhunt** [comment]
- Admin can navigate to the QR detection page on route `/qrScanner`
- Camera is open by default
- When scan is successful, page updates to display all user info. With 2 button to either rescan or checkIn the user.

On branch: qrcode-detection
